//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inbox2.Framework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inbox2.Framework.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has already been configured.
        /// </summary>
        public static string AccountAlreadyAdded {
            get {
                return ResourceManager.GetString("AccountAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose yes, then this account will also be removed from the Inbox2 cloud and any connected Inbox2 mobile applications..
        /// </summary>
        public static string AccountWillAlsoBeRemovedFromCloud {
            get {
                return ResourceManager.GetString("AccountWillAlsoBeRemovedFromCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding your {0} account has failed, please try again.
        /// </summary>
        public static string AddingAccountFailed {
            get {
                return ResourceManager.GetString("AddingAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All docked accounts.
        /// </summary>
        public static string AllDockedAccounts {
            get {
                return ResourceManager.GetString("AllDockedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox2 is already set as your default email client..
        /// </summary>
        public static string AlreadyDefaultMailClient {
            get {
                return ResourceManager.GetString("AlreadyDefaultMailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you also want to delete the associated conversation?
        ///
        ///Click conversation if you want to delete the selected message(s) and everything in the same conversation, click message if you just want to delete the selected message(s)..
        /// </summary>
        public static string AlsoDeleteConversations {
            get {
                return ResourceManager.GetString("AlsoDeleteConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always perform this check when starting Inbox2.
        /// </summary>
        public static string AlwaysPerformThisCheckDuringStartup {
            get {
                return ResourceManager.GetString("AlwaysPerformThisCheckDuringStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while deleting account &apos;{0}&apos;, please try again..
        /// </summary>
        public static string AnErrorHasOccuredWhileDeletingAccount {
            get {
                return ResourceManager.GetString("AnErrorHasOccuredWhileDeletingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured, please try again.
        /// </summary>
        public static string ANetworkErrorHasOccured {
            get {
                return ResourceManager.GetString("ANetworkErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this column? You can show this column again from options &gt;view..
        /// </summary>
        public static string AreYouSureYouWantToCloseColumn {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToCloseColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit? Doing so will cause you to lose any unsaved messages..
        /// </summary>
        public static string AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this account? .
        /// </summary>
        public static string AreYouSureYouWantToRemoveThisAccount {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatly {0} does not allow replies from Inbox2 yet..
        /// </summary>
        public static string ChannelDoesNotSupportReply {
            get {
                return ResourceManager.GetString("ChannelDoesNotSupportReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} accounts are not supported by the Inbox2 cloud infrastructure.
        /// </summary>
        public static string ChannelTypeNotSupportedInCloud {
            get {
                return ResourceManager.GetString("ChannelTypeNotSupportedInCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if there is an update available.
        /// </summary>
        public static string CheckingForUpdate {
            get {
                return ResourceManager.GetString("CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click ok to go to your {0} inbox..
        /// </summary>
        public static string ClickOkToReplyOn {
            get {
                return ResourceManager.GetString("ClickOkToReplyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an account failed, server said: &apos;{0}&apos;.
        /// </summary>
        public static string CreateAccountFailed {
            get {
                return ResourceManager.GetString("CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on while we create your account....
        /// </summary>
        public static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ask again (current action will be used as default).
        /// </summary>
        public static string DoNotAskAgain {
            get {
                return ResourceManager.GetString("DoNotAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update (download will continue if you close this window).
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft was saved successfully.
        /// </summary>
        public static string DraftSavedSuccessfully {
            get {
                return ResourceManager.GetString("DraftSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due to a channel error.
        /// </summary>
        public static string DueToAChannelError {
            get {
                return ResourceManager.GetString("DueToAChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due to an application error.
        /// </summary>
        public static string DueToAnApplicationError {
            get {
                return ResourceManager.GetString("DueToAnApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while sending your statis update to {0}, .
        /// </summary>
        public static string ErrorOccuredDuringStatusUpdate {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An upgrade is available for Inbox2, would you like to upgrade now? This process will take less then 30 seconds and is highly recommended..
        /// </summary>
        public static string Inbox2DetectedAnUpgrade {
            get {
                return ResourceManager.GetString("Inbox2DetectedAnUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading accounts and settings....
        /// </summary>
        public static string LoadingProfile {
            get {
                return ResourceManager.GetString("LoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, please verify your credentials and try again. Server said: &apos;{0}&apos;.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message has no body.
        /// </summary>
        public static string MessageHasNoBody {
            get {
                return ResourceManager.GetString("MessageHasNoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was sent successfully.
        /// </summary>
        public static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you are running in offline mode, your message will be sent when you are online again.
        /// </summary>
        public static string MessageWillBeSentLater {
            get {
                return ResourceManager.GetString("MessageWillBeSentLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help with adding {0}?.
        /// </summary>
        public static string NeedHelpConfiguring {
            get {
                return ResourceManager.GetString("NeedHelpConfiguring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but no help link is available for this {0}.
        /// </summary>
        public static string NoHelpLinkAvailable {
            get {
                return ResourceManager.GetString("NoHelpLinkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no important messages in your mailbox.
        /// </summary>
        public static string NoImportantMessages {
            get {
                return ResourceManager.GetString("NoImportantMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because you are not running under an admin account, you will be asked to give permissions to the upgrade process after you click yes..
        /// </summary>
        public static string NonAdminAccount {
            get {
                return ResourceManager.GetString("NonAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subject.
        /// </summary>
        public static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox2 is currently not your default email client. Click yes if you want set Inbox2 as your default email client..
        /// </summary>
        public static string NotYourDefaultMailClient {
            get {
                return ResourceManager.GetString("NotYourDefaultMailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already running the latest version of the Inbox2 desktop client.
        /// </summary>
        public static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can not be completed because there is no internet connection available.
        /// </summary>
        public static string OperationCouldNotBeCompletedDueToConnection {
            get {
                return ResourceManager.GetString("OperationCouldNotBeCompletedDueToConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create an account.
        /// </summary>
        public static string OrCreateAnAccount {
            get {
                return ResourceManager.GetString("OrCreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or login.
        /// </summary>
        public static string OrLogin {
            get {
                return ResourceManager.GetString("OrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the configuration correctly.
        /// </summary>
        public static string PleaseFillConfigurationCorrectly {
            get {
                return ResourceManager.GetString("PleaseFillConfigurationCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields to continue.
        /// </summary>
        public static string PleaseFillInAllFields {
            get {
                return ResourceManager.GetString("PleaseFillInAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a valid email address.
        /// </summary>
        public static string PleaseFillInAValidEmailAddress {
            get {
                return ResourceManager.GetString("PleaseFillInAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing account &apos;{0}&apos;, please wait....
        /// </summary>
        public static string RemovingAccount {
            get {
                return ResourceManager.GetString("RemovingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search documents.
        /// </summary>
        public static string SearchDocuments {
            get {
                return ResourceManager.GetString("SearchDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images.
        /// </summary>
        public static string SearchImages {
            get {
                return ResourceManager.GetString("SearchImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in your documents.
        /// </summary>
        public static string SearchInYourDocuments {
            get {
                return ResourceManager.GetString("SearchInYourDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in your images.
        /// </summary>
        public static string SearchInYourImages {
            get {
                return ResourceManager.GetString("SearchInYourImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message....
        /// </summary>
        public static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent items.
        /// </summary>
        public static string SentItems {
            get {
                return ResourceManager.GetString("SentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server said: {0}.
        /// </summary>
        public static string ServerSaid {
            get {
                return ResourceManager.GetString("ServerSaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read someday.
        /// </summary>
        public static string Someday {
            get {
                return ResourceManager.GetString("Someday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status was updated successfully.
        /// </summary>
        public static string StatusUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("StatusUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you are running in offline mode, your status will be updated when you are online again.
        /// </summary>
        public static string StatusWillBeUpdatedLater {
            get {
                return ResourceManager.GetString("StatusWillBeUpdatedLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to empty your trash folder? This action can not be undone!.
        /// </summary>
        public static string SureYouWantToEmptyTrash {
            get {
                return ResourceManager.GetString("SureYouWantToEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate to cloud.
        /// </summary>
        public static string SyncAuthError {
            get {
                return ResourceManager.GetString("SyncAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to cloud.
        /// </summary>
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to cloud....
        /// </summary>
        public static string SyncConnecting {
            get {
                return ResourceManager.GetString("SyncConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to cloud.
        /// </summary>
        public static string SyncNetError {
            get {
                return ResourceManager.GetString("SyncNetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to cloud.
        /// </summary>
        public static string SyncNotConnected {
            get {
                return ResourceManager.GetString("SyncNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing with cloud - {0}%.
        /// </summary>
        public static string SyncSyncing {
            get {
                return ResourceManager.GetString("SyncSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could take a very long time depending on the size of your mailbox, are you sure you want to continue?.
        /// </summary>
        public static string ThisCouldTakeALongTime {
            get {
                return ResourceManager.GetString("ThisCouldTakeALongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all your saved question dialog preferences, are you sure you want to do this?.
        /// </summary>
        public static string ThisWillResetDialogs {
            get {
                return ResourceManager.GetString("ThisWillResetDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all your saved layout preferences, are you sure you want to do this?.
        /// </summary>
        public static string ThisWillResetLayout {
            get {
                return ResourceManager.GetString("ThisWillResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        public static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send message.
        /// </summary>
        public static string UnableToSendMessage {
            get {
                return ResourceManager.GetString("UnableToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while trying to download the update, please try again later.
        /// </summary>
        public static string UpdateDownloadError {
            get {
                return ResourceManager.GetString("UpdateDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded update successfully, please restart Inbox2 to apply the update.
        /// </summary>
        public static string UpdateDownloadFinished {
            get {
                return ResourceManager.GetString("UpdateDownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating status....
        /// </summary>
        public static string UpdatingStatus {
            get {
                return ResourceManager.GetString("UpdatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading database, please wait... (this could take a minute).
        /// </summary>
        public static string UpgradingDatabase {
            get {
                return ResourceManager.GetString("UpgradingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on while we verify your credentials....
        /// </summary>
        public static string VerifyingCredentials {
            get {
                return ResourceManager.GetString("VerifyingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all accounts.
        /// </summary>
        public static string ViewAllAccounts {
            get {
                return ResourceManager.GetString("ViewAllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for answer.
        /// </summary>
        public static string WaitingFor {
            get {
                return ResourceManager.GetString("WaitingFor", resourceCulture);
            }
        }
    }
}
